name: Daily Naukri Auto-Apply

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Microsoft Edge & Virtual Screen
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-edge.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-edge.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Keep Naukri Profile Highlighted
        uses: Prateek-Wayne/naukri-resume-action@v1
        with:
          username: ${{ secrets.NAUKRI_EMAIL }}
          password: ${{ secrets.NAUKRI_PASSWORD }}
          profile_id: ${{ secrets.NAUKRI_PROFILE_ID }}
          profile_summary: "Software Quality Assurance Engineer with 4.5 years of experience in manual testing and backend validation across diverse environments. Currently verifying the Apps section of the Creative Cloud Desktop application."

      - name: Run the Bot
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          FIRSTNAME: "Vinesh"
          LASTNAME: "Tiwari"
          KEYWORDS: "QA Engineer, Software Quality Assurance, Manual Testing, Backend Validation"
          LOCATION: "Delhi"
          MAX_APPLICATIONS: "50"
          PAGES_PER_KEYWORD: "1"
        run: |
          xvfb-run python Naukri-Edge.py
